# Generated by Django 4.0.4 on 2022-05-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='ticker',
            field=models.CharField(default='teste', max_length=500),
            preserve_default=False,
        ),
    ]
